### ISSUE TITLE
Is there a problem looking up b32.i2p addresses?

### ISSUE THREAD

**Issue by eyedeekay** [cryptix/goSam#1]
I am using this library to facilitate my own project and I've hit a snag. No matter what I do, I can't seem to get it to retrieve a b32.i2p url successfully, every single time I try it returns an "INVALID_KEY" error. I did some digging and I see under [Host Name Lookup on the SAMv3 documentation page](https://geti2p.net/en/docs/api/samv3) that for uncached network connections, a lookup will fail on some implementations. As far as I can tell, this is what's happening to me. Is there something I should be doing to make b32 destinations work with the existing library?

**Comment by cryptix** [comment]
Hmm... sorry to hear that.

Have you tried resolving the address by hand using telnet/netcat against the SAM server? If that works it would mean it is a problem with this client lib.

**Comment by eyedeekay** [comment]
Lookup seems to work if I use telnet. If it matters, I set HELLO MIN and MAX to the same parameters as in the library(3.0) and immediately did the lookup against one of the b32 addresses I was attempting to retrieve in my application.

**Comment by cryptix** [comment]
Sorry, I don't have the capacity right now to reproduce this. 

Have you tried setting [ConnDebug](https://github.com/cryptix/goSam/blob/master/client.go#L12) to `true` and see if there is a difference between the calls?

**Comment by eyedeekay** [comment]
I had, but I took another look and I think I might see the problem now. I'm going to try some stuff and get back to you on it.
